config/routes.rb
Rails.application.routes.draw do
  get 'shift_requests/new'
  get 'shift_requests/create'
  get 'shift_requests/index'
  get 'attendance_corrections/new'
  get 'attendance_corrections/create'
  get 'attendance_corrections/index'
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  get "up" => "rails/health#show", as: :rails_health_check

  resources :attendances, only: [:index, :create, :new]
  resources :leave_applications, only: [:new, :create, :index]
  resources :expense_applications, only: [:new, :create, :index]
  resources :attendance_corrections, only: [:new, :create, :index]
  resources :shift_requests, only: [:index] do
    collection do
      get  :monthly_new
      post :monthly_create
    end
  end

  namespace :admin do
    resources :attendance_corrections, only: [:index, :update]
    resources :leave_applications, only: [:index, :update]
    resources :expense_applications, only: [:index, :update]
    resources :shift_requests, only: [:index, :update]
  end

  root to: 'home#index' 
end

app/models/leave_application.rb
class LeaveApplication < ApplicationRecord
  belongs_to :user

  validates :start_date, :end_date, :reason, presence: true

  enum status: { pending: 0, approved: 1, rejected: 2 }
  
  def status_i18n
    I18n.t("activerecord.attributes.leave_application.status.#{status}")
  end
end

app/controllers/admin/leave_applications_controller.rb
class Admin::LeaveApplicationsController < ApplicationController
  def index
    @leave_applications = LeaveApplication.includes(:user).order(created_at: :desc)
  end

  def update
    @leave_application = LeaveApplication.find(params[:id])
    @leave_application.update(status: params[:status])
    redirect_to admin_leave_applications_path, notice: "申請を更新しました"
  end
end

app/controllers/leave_applications_controller.rb
class LeaveApplicationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @leave_application = LeaveApplication.new
  end

  def create
    @leave_application = current_user.leave_applications.build(leave_application_params)
    if @leave_application.save
      redirect_to root_path, notice: "休暇申請を送信しました"
    else
      render :new
    end
  end

  def index
    @leave_applications = current_user.leave_applications.order(created_at: :desc)
  end

  private

  def leave_application_params
    params.require(:leave_application).permit(:start_date, :end_date, :reason)
  end
end

app/helpers/admin/leave_applications_helper.rb
module Admin::LeaveApplicationsHelper
end

app/helpers/leave_applications_helper.rb
module LeaveApplicationsHelper
end

app/views/admin/leave_applications/index.html.haml
%h2 休暇申請管理

%table.table.table-striped
  %thead
    %tr
      %th 氏名
      %th 開始日
      %th 終了日
      %th 理由
      %th ステータス
      %th 操作
  %tbody
    - @leave_applications.each do |app|
      %tr
        %td= app.user.email
        %td= app.start_date
        %td= app.end_date
        %td= app.reason
        %td= app.status_i18n
        %td
          - unless app.approved? || app.rejected?
            = button_to "承認", admin_leave_application_path(app, status: :approved), method: :patch, class: "btn btn-success btn-sm"
            = button_to "却下", admin_leave_application_path(app, status: :rejected), method: :patch, class: "btn btn-danger btn-sm"

= link_to '戻る', root_path

app/views/admin/leave_applications/update.html.haml
%h1 Admin::LeaveApplications#update
%p Find me in app/views/admin/leave_applications/update.html.haml